HOC and utils was added
janis-commerce/app-push-notification pull request #2
Opened 2023-12-28 14:34 UTC by GonzaFran

LINK DE TICKET: *
https://janiscommerce.atlassian.net/browse/APPSRN-257
LINK DE SUBTAREA:
https://janiscommerce.atlassian.net/browse/APPSRN-259

DESCRIPCIÓN DEL REQUERIMIENTO: *

Contexto

Actualmente el usuario no se entera absolutamente de nada que esté fuera del mundo de la app. Por ejemplo, si entro una sesión que tiene entrega express, no hay manera de notificar al picker para que la inicie de una manera eficiente.
Necesidad

Contar con un package que se encargue de manejar la lógica para mostrar notificaciones push en la app.

DESCRIPCIÓN DE LA SOLUCIÓN: *

Se hicieron modificaciones en la configuraciones iniciales:

- Se agregó el archivo .eslintignore y se modificaron: eslintrc.js , gitignore y jest.config.json para poder validar los test del package.

Se creó un contexto para aislar la lógica del manejo y suscripción a notificaciones.
Se armó un hook (?) para obtener la información que haya en el provider (Hoy por hoy sólo retorna el deviceToken que se obtiene de firebase cloud messaging)

Se agregó la api utils subscribeNotifications, hoy por hoy no se va a usar porque quedan pendientes modificaciones por parte del back. La estructura utilizada fue copiada directamente de las apis que usamos en las apps.

Se agregaron utils para manejar la lógica de recepción y manejo de notificaciones:

- Se agregó `setupForegroundMessageHandler` que maneja las notificaciones en primer plano y recibe una callback por parametro para manejar la información que se obtenga desde la notificación.
- Se agregó `setupBackgroundMessageHandler`, misma lógica que la utils de arriba pero orientada a manejar notificaciones en segundo plano y con la aplicación cerrada.
- Se agregaron `topicsSubscription` y `topicsUnsubscription` que funcionan para suscribirse y desuscribirse de topicos respectivamente. Los tópicos vendrían a ser los temas a los que se quiere suscribir al usuario.
- Se agregó un componente DefaultAlert, que se encarga de manejar la información recibida en la notificación y que sólo se usa en un caso que lo explico más abajo.
- Se agregó `getFCMToken` que se encarga de obtener el token del dispositivo y guardarlo en async storage.

Se agregaron las siguientes dependencias para el funcionamiento del package:

- async storage para guardar el token
- axios para hacer la request en las apis
- device info para obtener la información del dispositivo, también para las apis.
- nock para el testing de las apis
- prettier y babel/eslint-parser para corregir y validar el código.

Se agregó el HOC NotificationProvider, el cual se utiliza para “envolver” otros componentes y funcionar como un provider que se encargue de escuchar las notificaciones emitidas por Firebase.

Para poder funcionar y renderizarse, el HOC debe recibir de manera obligatoria un children.
También recibe otros parametros cómo foregroundCallback y backgroundCallback, que se usan en  `setupForegroundMessageHandler`  `setupBackgroundMessageHandler` respectivamente (previamente, se valida que sean funciones).
En caso de que foregroundCallback no pase la validación lo que se hace es pasar defaultAlert como callback para setupForegroundMessageHandler

El HOC también se encarga de obtener el token de firebase, que será conocido de ahora en más como FIREBASE CLOUD MESSAGING, o FCMToken para los amigos.

El token se obtiene cuando se renderiza la app mediante un useEffect y luego es guardado en asyncStorage.

Para las escucha de eventos de firebase se agregaron en el mismo useEffect las 2 utils armadas para estas funciones.

CÓMO SE PUEDE PROBAR? *

Se debe vincular el package a la app en la que se quiera probar, y también se debe agregar la siguiente dependencia:

`"@react-native-firebase/messaging": "^18.3.1"` que va a ser necesaria para que funcione la recepción de notificaciones.

Una vez instalada ambas dependencias lo que se debe hacer es usar el HOC NotificationProvider para envolver (en el main de la app) el MainStack;

`
import NotificationProvider from 'src/../.yalc/@janiscommerce/app-push-notification';

<NotificationProvider events={['notifications','testing','janis']}> //se ve más abajo
	<MainStack />
</NotificationProvider>

`

el provider puede recibir un parametro que es events, que serían los tópicos a los que quiero suscribir el dispositivo, por lo que, cuando quiera enviar un mensaje desde firebase puedo enviarlo a la aplicación o al tópico seleccionado. Para hacer esto se tiene que seleccionar la opción "temas" cuando se esté armando la notificación de prueba en el punto 2: orientación.

Para enviar un mensaje se debe hacer desde cloudMessaging en firebase:

![453052809-CLOUD_MESSAGING](https://github.com/janis-commerce/app-push-notification/assets/75044106/215299b1-2847-4f36-8530-4b981bcd3d94)

Una vez hecho esto se debería recibir el mensaje (esto puede demorar un rato largo)

SCREENSHOTS:

![530075877-notificacion en primer plano](https://github.com/janis-commerce/app-push-notification/assets/75044106/044199fd-0ef6-4973-a766-b9a3cf363436)

![3933996038-notificaciones en segundo plano](https://github.com/janis-commerce/app-push-notification/assets/75044106/93999b3e-6a7f-4d8f-a0c8-54a8e97b2f0b)

DATOS EXTRA A TENER EN CUENTA:

No se testean los metodos de suscripción y desuscripción a tópicos porque eventualmente serán eliminadas o descontinuadas porque, para estas suscripciones, se usará la api de notificationsSubscribe.

Se ignoró la linea correspondiente a la validación de backgroundCallback porque no supe cómo testear su ejecución (? se aceptan sugerencias.

Se agregaron lineas para evitar que validate-code rompa y se no se ejecute, las lineas son:

- ignorar la no utilización de validConfig.
- ignorar que registerDevice (la función que se usa para suscribir el dispositivo a notificaciones) no retorne nada.

2023-12-28 17:49 UTC, christian97dd requested changes

2023-12-28 17:49 UTC, christian97dd commented on lib/NotificationProvider/index.js
> +  const parsedConfig = {...validConfig, environment, events: validEvents};
esta variable la dejamos sin uso porque en un futuro se va a usar o la podemos volar?

2023-12-28 17:49 UTC, christian97dd commented on lib/NotificationProvider/index.js
> +    getDeviceToken();
ojo que esta funcion es asincronica, te faltaría un await

2023-12-28 17:49 UTC, christian97dd commented on test/utils/index.test.js
> +      expect(alertSpy).toBeCalledWith('A new FCM message arrived!', undefined);
fijate que estos `toBeCalledWith` están deprecados a favor de `toHaveBeenCalledWith`

2023-12-28 17:49 UTC, christian97dd commented on test/NotificationContext.test.js
> +    expect(React.useContext).toBeCalledWith(NotificationContext);
lo mismo este, usar `toHaveBeenCalledWith` porque el otro está deprecado

2023-12-28 18:03 UTC, GonzaFran commented on lib/NotificationProvider/index.js
> +  const parsedConfig = {...validConfig, environment, events: validEvents};
La vamos a usar más adelante, pero para pasarla a la api de suscripción, sólo que la dejo preparada para no tener que hacerlo después y no olvidarme cuáles son las props que necesita (?

2023-12-28 19:59 UTC, christian97dd approved these changes

2023-12-28 19:59 UTC, christian97dd commented on lib/NotificationProvider/index.js
> +  const parsedConfig = {...validConfig, environment, events: validEvents};
joyaa

2023-12-28 21:30 UTC, Maukr commented on lib/NotificationProvider/index.js
> +    await getDeviceToken();
@GonzaFran Estuve haciendo pruebas y me di cuenta que apenas abro la APP no guarda los tópicos o events ('notifications', 'testing' y el que le pasemos).
Esto es porque en la línea 49 se toma el valor del estado `deviceToken` que en esa instancia no parece haberse actualizado y sigue null a pesar de que el `getFCMToken` devolvió bien y el `setDeviceToken(fcmToken)` de la linea 42 se ejecutó.
Como solución el device token podría setear el estado y retornar el string:
```
  const getDeviceToken = async () => {
    const fcmToken = await getFCMToken();
    if (!fcmToken || !isString(fcmToken)) return null;
    setDeviceToken(fcmToken);
    return fcmToken;
  };
```
Y desde  `registerDevice`  obtenemos ese `string` y comparamos usandolo a él:

```
 const registerDevice = async () => {
     const newDeviceToken =  await getDeviceToken();
// usar el newDeviceToken para la condición
     if (!newDeviceToken) return null;
    // eslint-disable-next-line
    validEvents.forEach(async (event) => {
      if (!event || !isString(event)) return null;
      await topicsSubscription(event);
    });
  };
```
Si no se entendió lo vemos aparte, no hay problema

2023-12-29 14:02 UTC, GonzaFran commented on lib/NotificationProvider/index.js
> +    await getDeviceToken();
@Maukr listo los cambios propuestos, gracias por la solución!

2023-12-29 14:47 UTC, Maukr requested changes

2023-12-29 14:47 UTC, Maukr commented on lib/utils/index.js
> +    if (!topics || !isArray(topics)) return null;
@GonzaFran Acá el parámetro debería ser `topic` y deberíamos esperar un String, por ende la condición sería

`if (!topics || !isString(topics)) return null;`

Fijate que la util la utilizamos de esta manera:
```
validEvents.forEach(async (event) => {
			console.log('event', event);
			if (!event || !isString(event)) return null;
			await topicsSubscription(event);
		});
```
Lo que le estamos pasando es un string, no un array. Por eso no me está subscribiendo a los topics.

2023-12-29 15:33 UTC, GonzaFran commented on lib/utils/index.js
> +    if (!topics || !isArray(topics)) return null;
@Maukr listo el cambio

2023-12-29 15:55 UTC, Maukr approved these changes
Listo, ahí me llegó la notificación a través de un topic:
![image](https://github.com/janis-commerce/app-push-notification/assets/61480380/1ec395ea-13cc-41ce-80ba-20e135d94cb8)

2024-01-04 21:51 UTC, pablodamianberdun approved these changes

2024-01-04 21:51 UTC, merged